name: 🗑️ Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Type "DESTROY" to confirm'
        required: true
        default: ''

env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.6.0

jobs:
  terraform-destroy:
    name: 🚨 Terraform Destroy
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Validate Destroy Confirmation
      run: |
        if [ "${{ github.event.inputs.confirm_destroy }}" != "DESTROY" ]; then
          echo "❌ Destroy confirmation failed. You must type 'DESTROY' to proceed."
          exit 1
        fi
        echo "✅ Destroy confirmation validated"

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan Destroy
      run: terraform plan -destroy -out=tfplan-destroy

    - name: Terraform Destroy
      run: terraform apply -auto-approve tfplan-destroy

    - name: Destroy Summary
      run: |
        echo "## 🗑️ Infrastructure Destroyed!" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "All AWS resources have been successfully destroyed." >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### ⏰ Destroy Time:" >> $GITHUB_STEP_SUMMARY
        echo "$(date)" >> $GITHUB_STEP_SUMMARY
